cd /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L60.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L61.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L62.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L63.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L65.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L66.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L67.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L68.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L69.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L7.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L70.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L71.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L72.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L73.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L74.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L75.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L76.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L77.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L78.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L79.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
echo finished batch 14 of 16
perl -pi -w -e 's/!/N/g;' *.fasta
exit 0
