cd /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L117.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L118.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L119.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L12.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L120.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L121.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L122.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L123.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L124.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L125.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L126.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L127.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L128.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L129.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L13.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L130.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L131.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L132.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L133.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L134.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
echo finished batch 2 of 16
perl -pi -w -e 's/!/N/g;' *.fasta
exit 0
