cd /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L208.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L209.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L21.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L210.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L211.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L212.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L213.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L214.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L215.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L216.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L217.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L218.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L219.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L22.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L220.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L221.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L222.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L223.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L224.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
java -jar /Applications/macse_v2.03.jar -prog refineAlignment -align /Users/ianbrennan/Documents/GitHub/Crown_Frogs/Myobatrachidae/Original_Alignments/Myobatrachidae_L225.fasta -optim 1 -local_realign_init 0.1 -local_realign_dec 0.1 -fs 10
echo finished batch 7 of 16
perl -pi -w -e 's/!/N/g;' *.fasta
exit 0
